steps:
  - label: 'stack rebuild'
    env:
      # fixme: bucket in eu-central-1 is better for buildkite agents
      AWS_REGION: us-west-1
      S3_BUCKET: appveyor-ci-cache
      CACHE_S3_MAX_SIZE: 2500MB
    command:
      # cache-s3 needs a build directory that is the same across all buildkite agents.
      # so copy the source into /tmp/build/cardano-sl
      - "rm -rf /tmp/build/cardano-sl"
      - "mkdir -p /tmp/build"
      - "git clone . /tmp/build/cardano-sl"
      - "cd /tmp/build/cardano-sl"
      - "nix-build scripts/ci/buildkite -o stack-rebuild"
      - "./stack-rebuild"
    agents:
      system: x86_64-linux
